export const GET_ALL = 'GET_ALL'
export const GET_BY_ID = 'GET_BY_ID'
export const GET_BY_NAME = 'GET_BY_NAME'
export const CREATE_VIDEOGAME = 'CREATE_VIDEOGAME'
export const NAME_SEARCHED = 'NAME_SEARCHED'
export const CLEAN = 'CLEAN'
export const ERROR_VIDEOGAME = 'ERROR_VIDEOGAME'